---
- name: Install MySQL
  apt: pkg=mysql-server state=present

- name: Ensure MySQL is running
  service: name=mysql state=started enabled=true

- name: Copy root PW config file to /root/.my.cnf
  template: src=.my.cnf.j2
            dest=/root/.my.cnf

- name: Set root MySQL user password
  mysql_user:
    name: root
    password: "{{ mysql_root_pass }}"
    check_implicit_admin: true

- name: Create a new database with name '{{ dbname }}'
  mysql_db:
    name: "{{ dbname }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  notify:
    - restart mysql

- mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpassword }}"
    priv: '*.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  notify:
    - restart mysql

- mysql_user:
    name: "{{ phpmyadmin_mysql_user }}"
    password: "{{ phpmyadmin_mysql_password }}"
    priv: '*.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  notify:
    - restart mysql