- name: Add ondrej/php PPA
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install php5.6
  apt: name={{ item }} state=present
  with_items:
    - php5.6
    - php5.6-dev
    - php5.6-common
    - php5.6-mysql
    - php5.6-zip
    - php5.6-bz2
    - php5.6-cli
    - php5.6-curl
    - php5.6-gd
    - php5.6-cgi
    - php5.6-mcrypt
    - php5.6-memcache
    - php5.6-pspell
    - php5.6-xml
    - php5.6-xmlrpc
    - php5.6-xsl
    - php5.6-sqlite3
    - php5.6-snmp
    - php5.6-opcache
    - php5.6-mbstring
    - php5.6-imap
    - php5.6-json
    - php5.6-readline
    - php-pear
    - php-imagick
    - libapache2-mod-php5.6

- name: Enable php5mcrypt module
  shell: phpenmod mcrypt

- lineinfile:
    path: /etc/php/5.6/apache2/php.ini
    regexp: '^upload_max_filesize ='
    line: 'upload_max_filesize = 50M'

- lineinfile:
    path: /etc/php/5.6/apache2/php.ini
    regexp: '^post_max_size ='
    line: 'post_max_size = 50M'

- name: Restart apache2
  service: name=apache2 state=restarted